#!/bin/bash
args=$@
conclusions=${args%from*}
premises=${args#*from}
cd steps
cat settings $conclusions | \
sed 's/formulas(assumptions)/formulas(goals)/' | \
cat - $premises | \
prover9 #> /dev/null 2>&1
