#!/bin/bash
#set -x

# Check all the arguments specified in the 'arguments' file. Well, actually,
# check only the lines in that file that begin with '+'. That way you can put
# arguments in there that you're not ready to check.

function echo_color() {
    echo -ne "\033[01;$1m$2\033[00m"
}

powerset() { [ $# -eq 0 ] && echo || (shift; powerset "$@") |
            while read r ; do echo -e "$1 $r\n$r"; done }

test_shorter_paths() {
    conclusion=`echo $@ | sed "s/ from .*$//"`
    premises=`echo $@ | sed "s/^.* from //"`
    powerset $premises | while read subset; do

        # Only use proper subsets.
        if [[ $subset = $premises ]]; then continue; fi

        # Attempt to establish the same conclusion using fewer premises.
        demonstrate $conclusion from $subset

        # It's not supposed to work. If it does, yell.
        if [[ $? = 0 ]]; then
            echo_color 99 "  "
            echo_color 46 " "
            echo_color 99 " alt     "
            echo "$conclusion <- $subset"
        fi
    done
}

cat run_these | while read arg; do
    first_letter=${arg:0:1}
    d=${arg:1}
    if [[ $first_letter = "+" ]]; then
        demonstrate $d
        if [[ $? = 0 ]]; then
            echo_color 42 " "
            echo_color 99 " valid  "
            echo -n "   "
            args=`echo $d | sed "s/from/<-/"`
            echo_color 99 "$args"
            echo
            # disable for now
            # test_shorter_paths $d
        else
            echo_color 99 " "
            echo_color 45 " "
            echo_color 99 " invalid  "
            args=`echo $d | sed "s/from/<-/"`
            echo_color 99 "$args"
            echo
        fi
    fi
done

# test that no combination of premises raises a syntax error
#test_shorter_paths "true" from 1def3 misc 1p21 1p22 1p24c 1p25c 1p26 misc
